version: '3'
services:
  php:
      container_name: php
      build: ./php
      volumes:
      - ./src:/var/www
  nginx:
      image: nginx:stable-alpine
      ports:
      - "8080:80"
      volumes:
          - ./src:/var/www
          - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      depends_on:
      - php
